base_dev_dir: /data/peilin/xskill

hydra:
  run:
    dir: '${exp_path}/label'

exp_path: null
ckpt: null
device: null
resize_shape: [320, 230]
augmentations: ['center_crop_110_146', 'normalize']

datasets:
  human:
    data_path: 'TBD'
    save_path: 'TBD'
    camera_view: cam1
    mask_path: null
    name: null
    resize_shape: null
  robot:
    data_path: 'TBD'
    save_path: 'TBD'
    camera_view: cam1
    mask_path: null
    name: null
    resize_shape: null
