base_dev_dir: /data/peilin/xskill

hydra:
  run:
    dir: '${base_dev_dir}/experiment/label_real_pick_mug/${now:%Y-%m-%d_%H-%M-%S}'

exp_path: null
save_path: ${exp_path}
ckpt: 499
device: 'cuda:0'

data_path: '${base_dev_dir}/data/processed/pick_red_mug'
mask_paths:
  robot: '${base_dev_dir}/data/processed/pick_red_mug/robot_mask_40.json'
  human: '${base_dev_dir}/data/processed/pick_red_mug/human_mask_100.json'

resize_shape: [320,240]
augmentations: ['center_crop_110_146', 'normalize']